// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://vinid.net/dieu-khoan-dieu-kien",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/web-hooks/logs/incoming": {
            "post": {
                "description": "Hook store log from Auth0",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[store logs]"
                ],
                "summary": "Store log from auth0",
                "parameters": [
                    {
                        "description": "Body message",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.logsDTOReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ginh.response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "meta": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/ginh.ResponseMeta"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "code": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ginh.response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "meta": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/ginh.ResponseMeta"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "code": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ginh.ResponseMeta": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "ginh.response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "meta": {
                    "type": "object"
                }
            }
        },
        "rest.logDTO": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/rest.logData"
                },
                "log_id": {
                    "type": "string"
                }
            }
        },
        "rest.logData": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_name": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "log_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "rest.logsDTOReq": {
            "type": "object",
            "properties": {
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.logDTO"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Incoming endpoints auth0 web hooks",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "Response Code",
            "externalDocs": {
                "description": "Mapping table",
                "url": "https://vinid-team.atlassian.net/wiki/spaces/IAM/pages/775645874/Authorization+response+code"
            }
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "incoming endpoints of custom auth0 web hooks",
	Description: "List APIs of incoming endpoints of custom auth0 web hooks",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
