definitions:
  ginh.ResponseMeta:
    properties:
      code:
        type: object
      message:
        type: string
    type: object
  ginh.response:
    properties:
      data:
        type: object
      meta:
        type: object
    type: object
  rest.logDTO:
    properties:
      data:
        $ref: '#/definitions/rest.logData'
      log_id:
        type: string
    type: object
  rest.logData:
    properties:
      client_id:
        type: string
      client_name:
        type: string
      date:
        type: string
      description:
        type: string
      ip:
        type: string
      log_id:
        type: string
      type:
        type: string
      user_agent:
        type: string
      user_id:
        type: string
    type: object
  rest.logsDTOReq:
    properties:
      logs:
        items:
          $ref: '#/definitions/rest.logDTO'
        type: array
    type: object
info:
  contact: {}
  description: List APIs of incoming endpoints of custom auth0 web hooks
  termsOfService: https://vinid.net/dieu-khoan-dieu-kien
  title: incoming endpoints of custom auth0 web hooks
  version: 1.0.0
paths:
  /web-hooks/logs/incoming:
    post:
      consumes:
      - application/json
      description: Hook store log from Auth0
      parameters:
      - description: Body message
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/rest.logsDTOReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginh.response'
            - properties:
                meta:
                  allOf:
                  - $ref: '#/definitions/ginh.ResponseMeta'
                  - properties:
                      code:
                        type: integer
                    type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/ginh.response'
            - properties:
                meta:
                  allOf:
                  - $ref: '#/definitions/ginh.ResponseMeta'
                  - properties:
                      code:
                        type: integer
                    type: object
              type: object
      summary: Store log from auth0
      tags:
      - '[store logs]'
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Incoming endpoints auth0 web hooks
    type: apiKey
swagger: "2.0"
tags:
- externalDocs:
    description: Mapping table
    url: https://vinid-team.atlassian.net/wiki/spaces/IAM/pages/775645874/Authorization+response+code
  name: Response Code
